spring:
  application:
    name: savebuddy

  datasource:
    url: jdbc:mysql://localhost:3306/savings_db?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DB_NAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          # Google OAuth2
          google:
            client-id: ${GOOGLE_ID}
            client-secret: ${GOOGLE_SECRET}
            scope:
              - profile
              - email
            # redirect-uri는 Spring Security OAuth2가 자동으로 처리하므로 제거

        # Google OAuth2 Provider 설정
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo
            user-name-attribute: id

server:
  port: 8080
  servlet:
    session:
      cookie:
        secure: true
        same-site: None
